import type { StudyDataset } from "./studyTypes";
import { withDerivedStudyDomainModel } from "./studyDomainModel";

const importedAt = "2026-05-29T20:00:00.000Z";

export const studySeedData: StudyDataset = withDerivedStudyDomainModel({
  projects: [
    {
      id: "signal-data-analysis",
      name: "Signal and Data Analysis",
      sourceRoot: "G:\\My Drive\\Bar-Ilan\\Signal and Data Analysis\\Quiz",
      importedAt,
      extractionWarnings: [
        "Some scanned quiz pages may need manual review before asset-dependent prompts are final.",
        "Question support is generated from extracted prompts and should be checked against official solutions.",
      ],
    },
  ],
  documents: [
    {
      id: "sda-quiz-2024",
      projectId: "signal-data-analysis",
      title: "Signal and Data Analysis Quiz 2024",
      sourcePath: "Quiz/2024.pdf",
      year: 2024,
      quizLabel: "Quiz 2024",
    },
    {
      id: "sda-quiz-2023",
      projectId: "signal-data-analysis",
      title: "Signal and Data Analysis Quiz 2023",
      sourcePath: "Quiz/2023.pdf",
      year: 2023,
      quizLabel: "Quiz 2023",
    },
    {
      id: "sda-quiz-2022",
      projectId: "signal-data-analysis",
      title: "Signal and Data Analysis Quiz 2022",
      sourcePath: "Quiz/2022.pdf",
      year: 2022,
      quizLabel: "Quiz 2022",
    },
  ],
  topicThreads: [
    {
      id: "topic-spike-train-statistics",
      projectId: "signal-data-analysis",
      topic: "Spike-train statistics",
      displayName: "Spike-train statistics",
      summary:
        "Estimate firing rates and variability from real spike-count observations, then connect the statistics to experimental interpretation.",
      priorityScore: 0.91,
      firstExposureComplete: false,
      status: "ready",
      createdAt: importedAt,
      updatedAt: importedAt,
    },
    {
      id: "topic-information-theory",
      projectId: "signal-data-analysis",
      topic: "Information theory",
      displayName: "Information theory",
      summary:
        "Work with entropy, conditional entropy, and mutual information while keeping units and probability normalization explicit.",
      priorityScore: 0.84,
      firstExposureComplete: false,
      status: "ready",
      createdAt: importedAt,
      updatedAt: importedAt,
    },
    {
      id: "topic-bayes-map",
      projectId: "signal-data-analysis",
      topic: "ML/MAP/Bayes",
      displayName: "ML, MAP, and Bayes",
      summary:
        "Choose estimators by combining likelihoods, priors, and loss assumptions instead of memorizing formulas in isolation.",
      priorityScore: 0.78,
      firstExposureComplete: false,
      status: "ready",
      createdAt: importedAt,
      updatedAt: importedAt,
    },
    {
      id: "topic-roc-discrimination",
      projectId: "signal-data-analysis",
      topic: "ROC and discrimination",
      displayName: "ROC and discrimination",
      summary:
        "Compare decision thresholds with hit and false-alarm rates, then interpret the operating point and discrimination quality.",
      priorityScore: 0.69,
      firstExposureComplete: false,
      status: "ready",
      createdAt: importedAt,
      updatedAt: importedAt,
    },
  ],
  questions: [
    {
      id: "q-spike-2024-rate-fano",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2024",
      sourceAnchor: "2024.pdf#page=3&q=2",
      sourceYear: 2024,
      sourceQuizLabel: "Quiz 2024 Q2",
      rawPrompt:
        "A neuron is observed across 20 identical trials in a 500 ms window. The mean spike count is 8 and the count variance is 12. Estimate the firing rate in Hz, compute the Fano factor, and state whether the process appears more variable than Poisson.",
      normalizedPrompt:
        "Estimate firing rate and Fano factor from spike-count statistics and compare variability with a Poisson process.",
      pointValue: 12,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.96,
      createdAt: importedAt,
    },
    {
      id: "q-spike-2023-isi-cv",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2023",
      sourceAnchor: "2023.pdf#page=2&q=1",
      sourceYear: 2023,
      sourceQuizLabel: "Quiz 2023 Q1",
      rawPrompt:
        "Given inter-spike intervals with mean 25 ms and standard deviation 30 ms, compute the coefficient of variation. Explain what the value implies about regularity of the spike train.",
      normalizedPrompt:
        "Compute ISI coefficient of variation and interpret spike-train regularity.",
      pointValue: 8,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.94,
      createdAt: importedAt,
    },
    {
      id: "q-info-2024-mutual-info",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2024",
      sourceAnchor: "2024.pdf#page=5&q=4",
      sourceYear: 2024,
      sourceQuizLabel: "Quiz 2024 Q4",
      rawPrompt:
        "A binary stimulus S is equally likely. A binary response R matches S with probability 0.9. Compute H(S), H(S|R), and I(S;R) in bits. State why the result is below 1 bit.",
      normalizedPrompt:
        "Compute entropy, conditional entropy, and mutual information for a noisy binary response channel.",
      pointValue: 14,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.93,
      createdAt: importedAt,
    },
    {
      id: "q-info-2022-entropy",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2022",
      sourceAnchor: "2022.pdf#page=4&q=3",
      sourceYear: 2022,
      sourceQuizLabel: "Quiz 2022 Q3",
      rawPrompt:
        "For a response variable with probabilities [1/2, 1/4, 1/4], compute the entropy in bits and identify the most likely response state.",
      normalizedPrompt: "Compute entropy for a three-state response distribution.",
      pointValue: 7,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.97,
      createdAt: importedAt,
    },
    {
      id: "q-bayes-2023-map",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2023",
      sourceAnchor: "2023.pdf#page=6&q=5",
      sourceYear: 2023,
      sourceQuizLabel: "Quiz 2023 Q5",
      rawPrompt:
        "Two hypotheses have priors P(H1)=0.7 and P(H2)=0.3. The observed data likelihoods are P(x|H1)=0.2 and P(x|H2)=0.6. Compute the posterior odds and choose the MAP hypothesis.",
      normalizedPrompt:
        "Compute posterior odds from priors and likelihoods, then choose the MAP hypothesis.",
      pointValue: 10,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.95,
      createdAt: importedAt,
    },
    {
      id: "q-bayes-2022-ml-vs-map",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2022",
      sourceAnchor: "2022.pdf#page=5&q=4",
      sourceYear: 2022,
      sourceQuizLabel: "Quiz 2022 Q4",
      rawPrompt:
        "Explain why maximum likelihood and MAP estimates can select different hypotheses. Give one condition where they become identical.",
      normalizedPrompt:
        "Explain the relationship between ML and MAP estimates and when they coincide.",
      pointValue: 9,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.91,
      createdAt: importedAt,
    },
    {
      id: "q-roc-2024-threshold",
      projectId: "signal-data-analysis",
      documentId: "sda-quiz-2024",
      sourceAnchor: "2024.pdf#page=7&q=6",
      sourceYear: 2024,
      sourceQuizLabel: "Quiz 2024 Q6",
      rawPrompt:
        "A detector threshold gives 45 hits out of 50 signal trials and 10 false alarms out of 50 noise trials. Compute hit rate and false-alarm rate, then describe how raising the threshold usually changes both rates.",
      normalizedPrompt: "Compute ROC operating point rates and describe threshold effects.",
      pointValue: 11,
      isRealQuestion: true,
      generatedFromQuestionIds: [],
      dependsOnAssets: false,
      extractionConfidence: 0.92,
      createdAt: importedAt,
    },
  ],
  questionTopics: [
    {
      id: "qt-spike-2024-rate-fano",
      questionId: "q-spike-2024-rate-fano",
      topicThreadId: "topic-spike-train-statistics",
      topic: "Spike-train statistics",
      subtype: "Firing-rate and Fano factor",
      confidence: 0.96,
      isPrimary: true,
    },
    {
      id: "qt-spike-2023-isi-cv",
      questionId: "q-spike-2023-isi-cv",
      topicThreadId: "topic-spike-train-statistics",
      topic: "Spike-train statistics",
      subtype: "ISI variability",
      confidence: 0.95,
      isPrimary: true,
    },
    {
      id: "qt-info-2024-mutual-info",
      questionId: "q-info-2024-mutual-info",
      topicThreadId: "topic-information-theory",
      topic: "Information theory",
      subtype: "Mutual information",
      confidence: 0.94,
      isPrimary: true,
    },
    {
      id: "qt-info-2022-entropy",
      questionId: "q-info-2022-entropy",
      topicThreadId: "topic-information-theory",
      topic: "Information theory",
      subtype: "Entropy",
      confidence: 0.97,
      isPrimary: true,
    },
    {
      id: "qt-bayes-2023-map",
      questionId: "q-bayes-2023-map",
      topicThreadId: "topic-bayes-map",
      topic: "ML/MAP/Bayes",
      subtype: "MAP decision",
      confidence: 0.96,
      isPrimary: true,
    },
    {
      id: "qt-bayes-2022-ml-vs-map",
      questionId: "q-bayes-2022-ml-vs-map",
      topicThreadId: "topic-bayes-map",
      topic: "ML/MAP/Bayes",
      subtype: "Estimator comparison",
      confidence: 0.9,
      isPrimary: true,
    },
    {
      id: "qt-roc-2024-threshold",
      questionId: "q-roc-2024-threshold",
      topicThreadId: "topic-roc-discrimination",
      topic: "ROC and discrimination",
      subtype: "Threshold effects",
      confidence: 0.93,
      isPrimary: true,
    },
  ],
  topicModules: [
    {
      id: "module-topic-spike-train-statistics",
      projectId: "signal-data-analysis",
      topicClusterId: "cluster-topic-spike-train-statistics",
      theorySummaryMarkdown: [
        "Spike-train statistics describe how neurons fire over time. The same stimulus can produce different spike trains, so summarize spike trains using rate and variability measures.",
        "",
        "Core quantities:",
        "",
        "- Mean firing rate: `r = number of spikes / recording duration`",
        "- Inter-spike interval: `ISI_i = t_{i+1} - t_i`",
        "- Coefficient of variation: `CV = std(ISI) / mean(ISI)`",
        "- Fano factor: `FF = Var(spike count) / mean(spike count)`",
        "- Poisson benchmark: count mean equals variance, `FF = 1`, exponential ISIs, `CV = 1`, and constant hazard.",
        "",
        "Interpretation:",
        "",
        "- `CV < 1` or `FF < 1`: more regular than the Poisson benchmark.",
        "- `CV = 1` or `FF = 1`: Poisson-like for that statistic, but not proof of a Poisson process.",
        "- `CV > 1` or `FF > 1`: bursty, irregular, or over-dispersed activity.",
      ].join("\n"),
      formulaSheetMarkdown: [
        "- `r = N_spikes / T`",
        "- `ISI_i = t_{i+1} - t_i`",
        "- `CV = std(ISI) / mean(ISI)`",
        "- `FF = Var(N) / E[N]`",
        "- `P(n) = exp(-lambda) lambda^n / n!`, where `lambda = rT`",
        "- Homogeneous Poisson: `E[N] = Var(N) = lambda`, `CV = 1`, `FF = 1`",
      ].join("\n"),
      commonTrapsMarkdown: [
        "- `CV = 1` does not prove a process is Poissonian.",
        "- `FF = 1` in one window size does not guarantee `FF = 1` in every window size.",
        "- A refractory period violates the memoryless property of a homogeneous Poisson process.",
        "- CV and FF can disagree because they measure different aspects of spike statistics.",
      ].join("\n"),
      subtypeCoverageJson: {
        subtypes: [
          "Firing-rate and Fano factor",
          "ISI variability",
          "Poisson process",
          "Hazard function",
        ],
        highYieldSkills: [
          "Choose the statistic from the data type: counts, intervals, or hazard.",
          "Convert milliseconds to seconds before reporting Hz.",
          "Compare CV and FF with the Poisson benchmark without treating either as proof.",
        ],
        questionPatterns: [
          "Given spike counts across trials or windows, compute rate, variance, and Fano factor.",
          "Given ISIs, compute mean interval, CV, and regularity relative to Poisson.",
          "Given a spike-generation rule, reason about hazard, refractoriness, and whether the process is Poisson-like.",
        ],
        practiceDrills: [
          {
            title: "Poisson count statistics",
            sourceAnchors: ["Topic_01_Spike_Train_Statistics.md Problem 2"],
            promptMarkdown:
              "A homogeneous Poisson neuron fires at a given rate. Compute expected count, count variance, Fano factor, and the probability of observing zero spikes in a fixed window.",
          },
          {
            title: "CV from ISIs",
            sourceAnchors: ["Topic_01_Spike_Train_Statistics.md Problem 3"],
            promptMarkdown:
              "Given a short list of inter-spike intervals, compute mean ISI, population standard deviation, CV, and interpret regularity.",
          },
        ],
        studyFlow: [
          "Identify whether the data are counts, ISIs, or a hazard rule.",
          "Convert time units before computing rates.",
          "Compute the requested statistic.",
          "Compare against the Poisson benchmark and state the interpretation.",
        ],
      },
      firstExposureComplete: false,
    },
    {
      id: "module-topic-information-theory",
      projectId: "signal-data-analysis",
      topicClusterId: "cluster-topic-information-theory",
      theorySummaryMarkdown: [
        "Information theory measures uncertainty and how much uncertainty is reduced by observing data.",
        "",
        "Core quantities:",
        "",
        "- Surprise of one outcome: `h(x) = -log2 p(x)`",
        "- Entropy: `H(X) = - sum_x p(x) log2 p(x)`",
        "- Joint entropy: `H(X,Y) = - sum_x sum_y p(x,y) log2 p(x,y)`",
        "- Conditional entropy: `H(X|Y) = H(X,Y) - H(Y)`",
        "- Mutual information: `I(X;Y) = H(X) - H(X|Y)`",
        "",
        "Interpretation:",
        "",
        "- `H(X)` is uncertainty about `X`.",
        "- `H(X|Y)` is uncertainty remaining after knowing `Y`.",
        "- `I(X;Y)` is how much knowing `Y` tells us about `X`.",
        "- Independent variables have `I(X;Y) = 0`; perfect determination gives `H(X|Y) = 0`.",
      ].join("\n"),
      formulaSheetMarkdown: [
        "- `h(x) = -log2 p(x)`",
        "- `H(X) = -sum_x p(x) log2 p(x)`",
        "- `H(X,Y) = -sum_x sum_y p(x,y) log2 p(x,y)`",
        "- `H(X|Y) = H(X,Y) - H(Y)`",
        "- `I(X;Y) = H(X) - H(X|Y)`",
        "- `I(X;Y) = H(X) + H(Y) - H(X,Y)`",
        "- Useful values: `log2(1/2) = -1`, `log2(1/4) = -2`, `log2(0.1) ~= -3.322`, `log2(0.9) ~= -0.152`",
      ].join("\n"),
      commonTrapsMarkdown: [
        "- Do not confuse entropy with probability. Entropy is a weighted average of surprise.",
        "- `H(X,Y)` is not always `H(X) + H(Y)`; that only holds for independent variables.",
        "- Conditional entropy and mutual information cannot be negative.",
        "- Spike count can lose information contained in spike timing.",
      ].join("\n"),
      subtypeCoverageJson: {
        subtypes: ["Entropy", "Conditional entropy", "Mutual information", "Spike-pattern entropy"],
        highYieldSkills: [
          "Build the probability table before computing entropy.",
          "Compute marginals explicitly before using joint or conditional identities.",
          "Explain each result as uncertainty or uncertainty reduction.",
        ],
        questionPatterns: [
          "Compute entropy for categorical or binary state distributions.",
          "Compute conditional entropy and mutual information from deterministic or noisy features.",
          "Compare spike-pattern entropy with spike-count entropy and explain what timing adds.",
        ],
        practiceDrills: [
          {
            title: "Entropy of disease states",
            sourceAnchors: ["Topic_02_Information_Theory.md Problem 1"],
            promptMarkdown:
              "Given four state probabilities, compute entropy, compare it to the maximum entropy for four states, and interpret the distribution.",
          },
          {
            title: "Neuron response information",
            sourceAnchors: ["Topic_02_Information_Theory.md Problem 7"],
            promptMarkdown:
              "Given liquid priors and spike probabilities by liquid, compute conditional response entropy, response entropy, and mutual information.",
          },
        ],
        studyFlow: [
          "Write the full probability table.",
          "Check normalization and compute marginals.",
          "Choose the entropy identity that matches the question.",
          "Compute in bits and explain the interpretation.",
        ],
      },
      firstExposureComplete: false,
    },
    {
      id: "module-topic-bayes-map",
      projectId: "signal-data-analysis",
      topicClusterId: "cluster-topic-bayes-map",
      theorySummaryMarkdown: [
        "ML and MAP are methods to infer which class generated data or which parameter best explains observations.",
        "",
        "Core quantities:",
        "",
        "- Likelihood `L(theta | x)`: probability or density of observing `x` given hypothesis or parameter `theta`.",
        "- Log-likelihood: summing logs is equivalent to multiplying independent probabilities.",
        "- MLE: `theta_MLE = argmax L(theta | x)`.",
        "- Prior `P(theta)`: initial probability before observing the data.",
        "- MAP: `theta_MAP = argmax [L(theta | x) P(theta)]`.",
        "- MAP reverses an MLE decision only when the prior overcomes the likelihood ratio.",
      ].join("\n"),
      formulaSheetMarkdown: [
        "- Independent samples: `L(theta | x) = product_i P(x_i | theta)`",
        "- `LL(theta) = sum_i ln P(x_i | theta)`",
        "- `theta_MLE = argmax L(theta | x)`",
        "- `theta_MAP = argmax L(theta | x) P(theta)`",
        "- Posterior odds: `P(H1|x) / P(H2|x) = [P(x|H1)P(H1)] / [P(x|H2)P(H2)]`",
        "- Normal log-likelihood: `LL = -(N/2)ln(2*pi*var) - sum_i (x_i - mu)^2 / (2*var)`",
      ].join("\n"),
      commonTrapsMarkdown: [
        "- Check uniform-distribution bounds before multiplying likelihoods; one impossible observation makes likelihood zero.",
        "- Include the normalizing constant when comparing Gaussian models with different variances.",
        "- A prior can break a flat MLE plateau in uniform parameter-estimation problems.",
        "- Apply logs only after confirming probabilities are positive.",
      ].join("\n"),
      subtypeCoverageJson: {
        subtypes: ["MAP decision", "Estimator comparison", "MLE", "Log-likelihood"],
        highYieldSkills: [
          "Separate likelihood evidence from prior probability.",
          "Use log-likelihood for independent samples instead of multiplying many small values.",
          "Check distribution support before doing arithmetic.",
        ],
        questionPatterns: [
          "Classify observations under competing uniform, Bernoulli, or normal models.",
          "Decide whether a prior changes an MLE into a different MAP choice.",
          "Find the MLE range for a uniform parameter and then apply a prior.",
        ],
        practiceDrills: [
          {
            title: "Uniform classification",
            sourceAnchors: ["Topic_03_ML_MAP_Bayes.md Problem 1"],
            promptMarkdown:
              "Given two uniform response models and class priors, compute MLE and MAP decisions for repeated observations.",
          },
          {
            title: "Uniform parameter estimation",
            sourceAnchors: ["Topic_03_ML_MAP_Bayes.md Problem 3"],
            promptMarkdown:
              "Given samples from a uniform range centered on an unknown parameter, find the MLE interval and explain how a monotone prior changes the MAP estimate.",
          },
        ],
        studyFlow: [
          "Check support and reject hypotheses with zero likelihood.",
          "Compute likelihood or log-likelihood under each hypothesis.",
          "For MAP, multiply by priors or add log-priors.",
          "Compare scores and state why the chosen estimator wins.",
        ],
      },
      firstExposureComplete: false,
    },
    {
      id: "module-topic-roc-discrimination",
      projectId: "signal-data-analysis",
      topicClusterId: "cluster-topic-roc-discrimination",
      theorySummaryMarkdown: [
        "ROC curves evaluate how well a system or neuron distinguishes between two states, such as target versus noise, using a threshold on firing rate or response.",
        "",
        "Core quantities:",
        "",
        "- Threshold `theta`: a decision rule such as `if response > theta, guess target`.",
        "- True positive rate / hit rate: probability of guessing target when the stimulus is target.",
        "- False positive rate / false-alarm rate: probability of guessing target when the stimulus is noise.",
        "- ROC curve: plot TPR against FPR as the threshold sweeps from high to low.",
        "- AUC: overall discrimination quality; `0.5` is chance and `1.0` is perfect.",
      ].join("\n"),
      formulaSheetMarkdown: [
        "- `TPR = P(response >= theta | target)`",
        "- `FPR = P(response >= theta | noise)`",
        "- For uniform distributions, probabilities are overlap lengths divided by total range length.",
        "- ROC points are plotted as `(FPR, TPR)`.",
        "- Trapezoid area: `width * (height_left + height_right) / 2`",
        "- `AUC = 0.5` chance, `AUC = 1` perfect discrimination.",
      ].join("\n"),
      commonTrapsMarkdown: [
        "- Plot ROC points as `(FPR, TPR)`, not `(TPR, FPR)`.",
        "- Keep the positive class consistent with the threshold rule.",
        "- For uniform distributions, check which intervals overlap the threshold region.",
        "- Use trapezoids, rectangles, and triangles carefully when computing AUC from straight segments.",
      ].join("\n"),
      subtypeCoverageJson: {
        subtypes: ["Threshold effects", "ROC curve", "AUC", "Uniform distributions"],
        highYieldSkills: [
          "Identify signal and noise classes before computing rates.",
          "Translate a threshold into right-tail probability under each distribution.",
          "Draw the ROC as threshold moves from strict to permissive.",
        ],
        questionPatterns: [
          "Compute TPR and FPR for selected thresholds.",
          "Draw ROC curves for overlapping uniform or triangular distributions.",
          "Compute AUC from piecewise-linear ROC segments.",
        ],
        practiceDrills: [
          {
            title: "Overlapping uniform ROC",
            sourceAnchors: ["Topic_05_ROC_Discrimination.md Problem 1"],
            promptMarkdown:
              "Given target and noise uniform response ranges plus a greater-than-threshold rule, compute ROC points and AUC.",
          },
          {
            title: "Triangular distribution ROC",
            sourceAnchors: ["Topic_05_ROC_Discrimination.md Problem 2"],
            promptMarkdown:
              "Given increasing and decreasing triangular response distributions, compute midpoint TPR/FPR and describe the ROC shape.",
          },
        ],
        studyFlow: [
          "Choose the positive class and threshold direction.",
          "Compute TPR and FPR at key thresholds.",
          "Plot points as `(FPR, TPR)`.",
          "Compute AUC from the resulting curve.",
        ],
      },
      firstExposureComplete: false,
    },
  ],
  questionSupport: [
    {
      id: "support-q-spike-2024-rate-fano",
      questionId: "q-spike-2024-rate-fano",
      summaryContext:
        "Use spike count per observation window for rate, and variance divided by mean for Fano factor.",
      expectedAnswer: ["16 Hz", "Fano factor 1.5", "more variable than Poisson"],
      rubric: [
        { label: "Converts 500 ms window to 0.5 s", points: 3, keywords: ["0.5", "500 ms"] },
        { label: "Computes firing rate as 8 / 0.5 = 16 Hz", points: 4, keywords: ["16", "hz"] },
        { label: "Computes Fano factor as 12 / 8 = 1.5", points: 3, keywords: ["1.5", "fano"] },
        {
          label: "Interprets Fano factor above 1 as more variable than Poisson",
          points: 2,
          keywords: ["poisson", "more variable", "overdispers"],
        },
      ],
      hints: [
        "Start by converting the observation window into seconds.",
        "The Fano factor is count variance divided by count mean.",
        "For a Poisson process, count variance equals count mean.",
      ],
      solutionSteps: [
        "The observation window is 500 ms, or 0.5 s.",
        "The firing rate is 8 spikes / 0.5 s = 16 Hz.",
        "The Fano factor is 12 / 8 = 1.5.",
        "A Fano factor larger than 1 suggests the counts are more variable than a Poisson process.",
      ],
      commonMistakes: [
        "Using 500 instead of 0.5 seconds.",
        "Dividing mean by variance for the Fano factor.",
        "Calling the process Poisson-like without comparing the factor to 1.",
      ],
      supportConfidence: 0.91,
      generatedAt: importedAt,
    },
    {
      id: "support-q-spike-2023-isi-cv",
      questionId: "q-spike-2023-isi-cv",
      summaryContext: "The coefficient of variation is standard deviation divided by mean.",
      expectedAnswer: ["CV = 1.2", "irregular spike train"],
      rubric: [
        {
          label: "Uses CV = standard deviation / mean",
          points: 3,
          keywords: ["std", "mean", "cv"],
        },
        { label: "Computes 30 / 25 = 1.2", points: 3, keywords: ["1.2", "30", "25"] },
        {
          label: "Interprets CV above 1 as irregular or bursty",
          points: 2,
          keywords: ["irregular", "bursty", "variable"],
        },
      ],
      hints: [
        "Use the same units for mean and standard deviation before dividing.",
        "A CV near 1 is Poisson-like; values above 1 are more irregular.",
      ],
      solutionSteps: [
        "Both values are in ms, so divide directly.",
        "CV = 30 ms / 25 ms = 1.2.",
        "A CV greater than 1 indicates more irregular timing than a Poisson-like renewal process.",
      ],
      commonMistakes: ["Subtracting instead of dividing.", "Treating CV as a value with units."],
      supportConfidence: 0.9,
      generatedAt: importedAt,
    },
    {
      id: "support-q-info-2024-mutual-info",
      questionId: "q-info-2024-mutual-info",
      summaryContext:
        "For a symmetric binary channel with accuracy 0.9, H(S)=1 bit and H(S|R)=H_b(0.1).",
      expectedAnswer: ["H(S)=1 bit", "H(S|R) about 0.469 bits", "I(S;R) about 0.531 bits"],
      rubric: [
        { label: "Identifies H(S) = 1 bit", points: 3, keywords: ["1", "bit", "h(s)"] },
        {
          label: "Computes binary error entropy H_b(0.1) around 0.469 bits",
          points: 5,
          keywords: ["0.469", "0.47", "conditional"],
        },
        {
          label: "Computes mutual information around 0.531 bits",
          points: 4,
          keywords: ["0.531", "0.53", "mutual"],
        },
        {
          label: "Explains noise makes information less than 1 bit",
          points: 2,
          keywords: ["noise", "below", "less than 1"],
        },
      ],
      hints: [
        "A fair binary stimulus has entropy 1 bit.",
        "The conditional uncertainty is the binary entropy of the error probability.",
        "Use I(S;R) = H(S) - H(S|R).",
      ],
      solutionSteps: [
        "Since S is equally likely and binary, H(S)=1 bit.",
        "The response has error probability 0.1, so H(S|R)=H_b(0.1) about 0.469 bits.",
        "I(S;R)=1 - 0.469 = 0.531 bits.",
        "The value is below 1 bit because response noise leaves residual uncertainty about S.",
      ],
      commonMistakes: [
        "Using natural logarithms without converting to bits.",
        "Reporting accuracy 0.9 as the mutual information.",
      ],
      supportConfidence: 0.87,
      generatedAt: importedAt,
    },
    {
      id: "support-q-info-2022-entropy",
      questionId: "q-info-2022-entropy",
      summaryContext: "Entropy is the sum of -p log2 p across response states.",
      expectedAnswer: ["1.5 bits", "state with probability 1/2"],
      rubric: [
        { label: "Uses -sum p log2 p", points: 3, keywords: ["log2", "entropy", "sum"] },
        { label: "Computes entropy as 1.5 bits", points: 3, keywords: ["1.5", "bits"] },
        {
          label: "Identifies the 1/2-probability response as most likely",
          points: 1,
          keywords: ["1/2", "most likely"],
        },
      ],
      hints: [
        "Evaluate each probability term separately.",
        "The largest probability marks the most likely state.",
      ],
      solutionSteps: [
        "H = -[1/2 log2(1/2) + 1/4 log2(1/4) + 1/4 log2(1/4)].",
        "The terms are 0.5, 0.5, and 0.5 bits.",
        "The total entropy is 1.5 bits, and the state with probability 1/2 is most likely.",
      ],
      commonMistakes: ["Forgetting the negative sign.", "Using ln and reporting nats as bits."],
      supportConfidence: 0.93,
      generatedAt: importedAt,
    },
    {
      id: "support-q-bayes-2023-map",
      questionId: "q-bayes-2023-map",
      summaryContext: "Posterior odds are prior odds multiplied by the likelihood ratio.",
      expectedAnswer: ["posterior odds H1:H2 = 7:9", "choose H2"],
      rubric: [
        {
          label: "Multiplies priors by likelihoods",
          points: 4,
          keywords: ["0.7", "0.2", "0.3", "0.6"],
        },
        {
          label: "Computes unnormalized posteriors 0.14 and 0.18",
          points: 3,
          keywords: ["0.14", "0.18"],
        },
        { label: "Chooses H2 as MAP", points: 3, keywords: ["h2", "map"] },
      ],
      hints: [
        "Compare P(H)P(x|H) for each hypothesis.",
        "You do not need the evidence term if you only need the MAP choice.",
      ],
      solutionSteps: [
        "For H1, P(H1)P(x|H1)=0.7*0.2=0.14.",
        "For H2, P(H2)P(x|H2)=0.3*0.6=0.18.",
        "The posterior odds H1:H2 are 0.14:0.18 = 7:9, so MAP selects H2.",
      ],
      commonMistakes: [
        "Choosing H1 from the prior alone.",
        "Choosing H2 from likelihood without showing posterior comparison.",
      ],
      supportConfidence: 0.91,
      generatedAt: importedAt,
    },
    {
      id: "support-q-bayes-2022-ml-vs-map",
      questionId: "q-bayes-2022-ml-vs-map",
      summaryContext: "ML uses likelihood only; MAP combines likelihood with the prior.",
      expectedAnswer: ["ML ignores prior", "MAP uses prior", "identical with uniform priors"],
      rubric: [
        { label: "Defines ML as maximizing likelihood", points: 3, keywords: ["likelihood", "ml"] },
        {
          label: "Defines MAP as maximizing posterior",
          points: 3,
          keywords: ["posterior", "prior", "map"],
        },
        {
          label: "States they match under uniform priors",
          points: 3,
          keywords: ["uniform", "same", "identical"],
        },
      ],
      hints: [
        "Ask whether the prior is included in the objective.",
        "A flat prior does not change the likelihood ranking.",
      ],
      solutionSteps: [
        "Maximum likelihood chooses the hypothesis with largest P(x|H).",
        "MAP chooses the hypothesis with largest P(H|x), equivalently P(x|H)P(H).",
        "They can differ when priors are unequal. They coincide when priors are uniform or otherwise do not change the ranking.",
      ],
      commonMistakes: [
        "Saying MAP is always better.",
        "Forgetting to name the equal-prior condition.",
      ],
      supportConfidence: 0.88,
      generatedAt: importedAt,
    },
    {
      id: "support-q-roc-2024-threshold",
      questionId: "q-roc-2024-threshold",
      summaryContext:
        "Hit rate and false-alarm rate are fractions over signal and noise trials respectively.",
      expectedAnswer: [
        "hit rate 0.9",
        "false-alarm rate 0.2",
        "raising threshold lowers both rates",
      ],
      rubric: [
        { label: "Computes hit rate 45/50 = 0.9", points: 4, keywords: ["0.9", "45", "50", "hit"] },
        {
          label: "Computes false-alarm rate 10/50 = 0.2",
          points: 4,
          keywords: ["0.2", "10", "50", "false"],
        },
        {
          label: "Explains raising threshold usually lowers hit and false-alarm rates",
          points: 3,
          keywords: ["threshold", "lower", "decrease"],
        },
      ],
      hints: [
        "Use signal trials as the denominator for hits.",
        "Use noise trials as the denominator for false alarms.",
        "A stricter threshold makes positive responses less frequent.",
      ],
      solutionSteps: [
        "Hit rate = 45 / 50 = 0.9.",
        "False-alarm rate = 10 / 50 = 0.2.",
        "Raising the threshold usually makes the detector more conservative, reducing both hit rate and false-alarm rate.",
      ],
      commonMistakes: [
        "Using all 100 trials as both denominators.",
        "Saying threshold changes only false alarms.",
      ],
      supportConfidence: 0.9,
      generatedAt: importedAt,
    },
  ],
});
